In [1]:
import numpy as np

array = np.random.randint(1, 100, 9)
print(array)

print(np.sqrt(array))

print(array.ndim)

new_array = array.reshape(3, 3)
print(new_array)

print(new_array.ndim)

print(new_array.ravel())

newm = new_array.reshape(3, 3)
print(newm)

print(newm[2, 1:3])

print(newm[1:2, 1:3])

print(new_array[0:3, 0:0])

print(new_array[0:2, 0:1])

print(new_array[0:3, 0:1])

print(new_array[1:3])

[49 78 92 59 32 27 59  7  6]
[7.         8.83176087 9.59166305 7.68114575 5.65685425 5.19615242
 7.68114575 2.64575131 2.44948974]
1
[[49 78 92]
 [59 32 27]
 [59  7  6]]
2
[49 78 92 59 32 27 59  7  6]
[[49 78 92]
 [59 32 27]
 [59  7  6]]
[7 6]
[[32 27]]
[]
[[49]
 [59]]
[[49]
 [59]
 [59]]
[[59 32 27]
 [59  7  6]]
